name: mlops_project
channels:
  - conda-forge
  - default

dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - openpyxl
  - pyyaml
  - python-dotenv
  - wandb
  - pytest
  - pytest-cov
  - black
  - flake8
  - pip